---
title: "Statisitcal Programming - 2020 - Project 1"
output: rmarkdown::html_document
author: Add your name here
---

Due on Monday, November 2nd by 5:00 pm (17:00), UK local time.

Before you start be sure to read through *all* of the rules and instructions in the `README.md`.

<br/>

### Data

```{r}
library(tidyverse)
f1 = readRDS(file="data/f1.rds")
```


<br/>

### Task 1 - Tidy the data

#### Write up

<!-- Include write up here -->

#### Code

```{r task1}
f1_tidy = f1 %>%
  tibble::tibble(f1 = .) %>%
  hoist(
    f1, 
    MRData = c("MRData")
  )%>%
  hoist(
    MRData,
    table = c("RaceTable")
  )%>%
  select(-MRData)%>%
  hoist(
    table,
    races = c("Races")
  )%>%
  select(-table)%>%
  unnest_longer(races)%>%
  hoist(
    races,
    race_name = c("raceName"),
    round = c("round"),
    date = c("date"),
    results = c("Results")
  )%>%
  mutate(date = as.Date(date))%>%
  mutate(round = as.integer(round))%>%
  select(-races)%>%
  unnest_longer(results)%>%
  hoist(
    results,
    driver_info = c("Driver"),
    constructor_info = c("Constructor"),
    position = c("position"),
    points = c("points")
  )%>%
  mutate(position = as.integer(position))%>%
  mutate(points = as.integer(points))%>%
  select(-results)%>%
  hoist(
    driver_info,
    first_name = c("givenName"),
    surname = c("familyName")
  )%>%
  select(-driver_info)%>%
  hoist(
    constructor_info,
    constructor = c("name")
  )%>%
  select(-constructor_info)%>%
  mutate(driver = paste(first_name, surname, sep=" "))%>%
  select(-first_name, -surname)%>%
  relocate(race_name, round, date, driver)

head(f1_tidy, 10)
```

<br/>


### Task 2 - Drivers' Championship

#### Write up

<!-- Include write up here -->

#### Code

```{r task2}

```

<br/>

### Task 3 - Cumulative Constructors

#### Write up

<!-- Include write up here -->

#### Code

```{r task3}

```

<br/>

### Task 4 - Visualization

#### Write up

<!-- Include write up here -->

#### Code

```{r task4}

```

<br/>

